
title: My Resume
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Reneal Rogers
tagline: Aspiring Software Craftsman 
pic: me.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: renealrogers@gmail.com
phone: 613 712 4009
website: fansua.io #do not add http://
linkedin: reneal-rogers/
github: fansua
#twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
